# .air.toml
[build]
  bin = "tmp/main" # Binary output
  cmd = "go build -o tmp/main ./app/main.go"
  include_ext = ["go", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor"]
  exclude_file = ["app/assets"]

[run]
  cmd = "./tmp/main"
  env = ["PORT=5050"]
